def print_help():
    print("Usage: python SyKit <command>")
    print("Commands operate on the current working directory.")
    print("Commands:")
    print("  init   Create src/sykit configuration and a minimal starter app")
    print("  build [--dev]  Generate endpoints and compile the production")
    print("                 application; --dev also runs the built app")
    print("  keys <generate|list|revoke>  Manage API keys for @api_key endpoints")
    print("  package <add|remove|list|diff>  Manage packages that extend SyKit")
    print("  update [source] [--yes] [--allow-unreleased]  Update SyKit")
    print("                 from a pinned release or explicitly allowed branch")
    print("  version  Show the SyKit source version")
    print("  help   Show this help")
