from __future__ import annotations

import contextlib
import io
import os
import tempfile
import unittest
from pathlib import Path

import build


class DockerFileGenerationTests(unittest.TestCase):
    def test_dockerfile_content(self) -> None:
        content = build.generate_dockerfile(8443)
        self.assertIn("FROM python:3.12-slim", content)
        self.assertIn("EXPOSE 8443", content)
        self.assertIn("requirements.txt", content)
        self.assertIn('CMD ["python", "main.py"]', content)
        self.assertIn("Generated by SyKit", content)

    def test_compose_content(self) -> None:
        content = build.generate_compose(8443)
        self.assertIn('- "8443:8443"', content)
        self.assertIn("SYKIT_SESSION_SECRET", content)
        self.assertIn("${SYKIT_SESSION_SECRET:?", content)
        self.assertIn("restart: unless-stopped", content)

    def test_dockerignore_excludes_state_files(self) -> None:
        for entry in (
            "__pycache__/",
            "*.pyc",
            ".sykit-limits.sqlite3",
            ".sykit-sessions.sqlite3",
        ):
            self.assertIn(entry, build.DOCKERIGNORE)


class WriteDockerFilesTests(unittest.TestCase):
    def setUp(self) -> None:
        self._directory = tempfile.TemporaryDirectory(prefix="sykit-deploy-test-")
        self.addCleanup(self._directory.cleanup)
        self._previous = Path.cwd()
        os.chdir(self._directory.name)
        self.addCleanup(os.chdir, self._previous)
        build.STAGING_DIR.mkdir()

    def _write(self, host: str) -> str:
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            build.write_docker_files(9000, host)
        return output.getvalue()

    def test_writes_all_three_files(self) -> None:
        output = self._write("0.0.0.0")
        for name in ("Dockerfile", "compose.yaml", ".dockerignore"):
            self.assertTrue((build.STAGING_DIR / name).is_file(), name)
        self.assertIn("Docker files written", output)
        self.assertNotIn("Warning", output)
        self.assertIn(
            "EXPOSE 9000",
            (build.STAGING_DIR / "Dockerfile").read_text(encoding="utf-8"),
        )

    def test_loopback_host_warns(self) -> None:
        for loopback in ("127.0.0.1", "localhost", "::1"):
            output = self._write(loopback)
            self.assertIn("Warning", output)
            self.assertIn("0.0.0.0", output)


if __name__ == "__main__":
    unittest.main()
